### PR TITLE
minor: addition of .sdcard file support

### PR DESCRIPTION
**Pull request by gromain**
Solves #1348, #1361.
Change discussed in #1360 (though this PR does not solve this issue), it is a temporary and simple fix to address part of this issue.

### CODE REVIEW

**Comment by gromain** [comment]
Should I reword my commits to follow the guidelines at [COMMIT-GUIDELINES](https://github.com/resin-io/etcher/blob/master/docs/COMMIT-GUIDELINES.md) ?
This is not clear from the [CONTRIBUTING](https://github.com/resin-io/etcher/blob/master/docs/CONTRIBUTING.md) .

**Comment by jhermsmeier** [comment]
@gromain you don't have to – the commits get squashed before merging anyways, and we can adjust the commit message there, but it would be great if they're in that form already. I've created an issue about that, and we shall fix the undiscoverability of the commit guidelines shortly.

**Comment by gromain** [comment]
Ok then, I'll reword then and force push it.
Thanks!

**Comment by gromain** [comment]
Also, it looks like the build failing at travis was from that it was unable to unpack some file.
> npm ERR! tar.unpack unzip error /tmp/npm-455-648d9e40/registry.npmjs.org/electron-winstaller-fixed/-/electron-winstaller-fixed-2.11.7.tgz

Is there anything I can do on my side to fix this?

**Comment by jhermsmeier** [comment]
> Ok then, I'll reword then and force push it.

Cool, thanks!

> Is there anything I can do on my side to fix this?

If it's the ZBUF error, nope – that occasionally happens due to network issues on Travis' side or npm wonkiness.

**Comment by jhermsmeier** [comment]
The Z_BUF_ERROR again, restarted the build jobs in question.

**Comment by gromain** [comment]
Thanks, looks like it went through this time!

**Comment by jviotti** [comment]
Awesome, thanks a lot @gromain !

**Comment by gromain** [comment]
No worries!

**Pull request merged**
