### PR TITLE
Suggest macOS alternative to Rufus

### PR DESCRIPTION
**Pull request by da2x**
* Specify that Rufus is only an option for Windows.
* Suggest Apple Boot Camp Assistant (built-in) as an alternative for macOS users.

Not sure what to suggest for Linux other than possibly the following online search:
[`Linux "ms-sys" bootable Windows ISO`](https://duckduckgo.com/?q=Linux%20%22ms-sys%22%20bootable%20Windows%20ISO)

### CODE REVIEW

**Comment by jviotti** [comment]
As far as I've seen, BootCamp is only a solution in a minority of cases (it refuses to create an external USB drive on later versions, handling everything external), but @jhermsmeier can probably tell.

**Comment by jhermsmeier** [comment]
Yeah, Boot Camp Assistant only flashes to USB thumb drives (no USB HDDs, no SD cards, etc afaik), so that makes it a bit of a limited alternative.

**Comment by da2x** [comment]
Still better than suggestion a Windows only alternative.

**Comment by jviotti** [comment]
Cool, yeah, up to @jhermsmeier really.

**Comment by jhermsmeier** [comment]
> Still better than suggestion a Windows only alternative.

Yeah definitely, I think so to – was just confirming the limitations.

**Comment by jviotti** [comment]
Awesome, thanks a lot @da2x !

**Pull request merged**
