### PR TITLE
test(lint): Update codespell 1.11.0 -> 1.12.0

### PR DESCRIPTION
**Pull request by jhermsmeier**
This updates codespell, and fixes new spelling error detections

```
lib/shared/models/selection-state.js:377: Unselect  ==> Deselect
lib/gui/app/components/modal/styles/_modal.scss:72: programatically  ==> programmatically
tests/shared/errors.spec.js:88: prioritise  ==> prioritize
tests/shared/errors.spec.js:94: prioritise  ==> prioritize
tests/shared/errors.spec.js:100: prioritise  ==> prioritize
tests/gui/components/svg-icon.spec.js:100: prioritise  ==> prioritize
docs/MAINTAINERS.md:19: artefacts  ==> artifacts
docs/MAINTAINERS.md:21: artefacts  ==> artifacts
docs/MAINTAINERS.md:25: artefacts  ==> artifacts
docs/MAINTAINERS.md:36: artefacts  ==> artifacts
docs/MAINTAINERS.md:96: artefacts  ==> artifacts
docs/MAINTAINERS.md:147: artefacts  ==> artifacts
CHANGELOG.md:492: interferring  ==> interfering
```

Change-Type: patch

### CODE REVIEW

**Comment by lurch** [comment]
I guess it depends if Etcher wants to use British English or American English?
http://grammarist.com/spelling/prioritize-vs-prioritise/
http://grammarist.com/spelling/artefact-artifact/

**Comment by jhermsmeier** [comment]
@lurch yeah, but I don't think that's a detail we should obsess over at this time ;P

**Comment by lurch** [comment]
It's of course entirely up to you... :)

(but IMVHO if the decision is made to use American spellings, then that decision should be applied everywhere, for consistency)

**Comment by jhermsmeier** [comment]
Yeah, true – is it not consistent atm?

**Pull request merged**
