### PR TITLE
feat(GUI): use tabindex and focus to navigate

### PR DESCRIPTION
**Pull request by Shou**
We make navigating with the tab key easier by highlighting focused
elements more visibly, adding `tabindex` attributes to elements, and
making `open-external` links respond to keyboard events.

Change-Type: minor
Changelog-Entry: Improve tab-key navigation through tabindex and visual
improvements.
Connects-To: #1734

### CODE REVIEW

**Comment by Shou** [comment]
This is part of an effort to make Etcher more accessible. @konmouz are there any "Resin-standard" ways of highlighting elements in an accessible manner? Right now I think only the footer elements are visible enough. Examples below.

Unselected button vs Selected button
image image
Selected SVG icon (same for text)
image
Selected help icon (unselected cog for comparison)
image

**Comment by Shou** [comment]
Looks like the HTML linter doesn't like Angular templates. @jviotti do you know how to get around this, e.g. disable it for a single line or something like that?

**Comment by konmouz** [comment]
@Shou, I can't find anything relevant in the style guide.

**Comment by jhermsmeier** [comment]
Relevant issue: https://github.com/resin-io/etcher/issues/1734

**Comment by jhermsmeier** [comment]
@Shou I fear that the difference in selection state of the button & icons is barely visible (I can barely make it out in the screenshots) – can we make the effect a bit more pronounced, or use an outline for them as well?

**Comment by Shou** [comment]
@jhermsmeier I agree with you fully. I was hoping to spawn discussion about it here, although on second thought we should use your issue instead as issues are more apt for potentially lengthy discussion.

**Comment by konmouz** [comment]
The orange frame seems to work fine. Can we have the same behaviour on all buttons?

**Comment by jhermsmeier** [comment]
Ah well, it's happened now. +1 on the orange outline for everything – that's the most familiar for everyone from browserland I guess.
And can you add that issue to the PR description as "Connects To:" (Change-Type is also missing), so we don't forget to close it once this gets merged?

**Comment by Shou** [comment]
How's this? Any tabbable element now uses the orange outlines, but they're also impermanent, with a 10 second timeout before the outlines disappear.

Also added `Change-Type` and `Connects-To`.

**Comment by jhermsmeier** [comment]
I'm getting blue outlines on Mac OS here, as their defaults are OS dependent – we'll need to explicitly set the color on them

screen shot 2017-09-28 at 17 40 25
screen shot 2017-09-28 at 17 40 30

**Comment by Shou** [comment]
Added an orange outline now.

**Comment by jhermsmeier** [comment]
Can we also get the padding on the top right buttons down so that the outline is evenly spaced?

screen shot 2017-10-03 at 15 19 52

**Comment by Shou** [comment]
This should be done now, but let me know if there's anything else

**Comment by jhermsmeier** [comment]
Just checked it out, looks good now! :)

**Pull request merged**
