### PR TITLE
chore: symlink manifests in dependencies scripts

### PR DESCRIPTION
**Pull request by jviotti**
See: https://github.com/resin-io/etcher/pull/934#issuecomment-264862767
Signed-off-by: Juan Cruz Viotti <jviotti@openmailbox.org>

### CODE REVIEW

**Comment by lurch** [comment]
Should do the same for `dependencies-npm.sh` too?

**Comment by lurch** [comment]
...and this now needs to be rebased ;)

**Comment by jviotti** [comment]
Yeah, I'll create another one for NPM.

> ...and this now needs to be rebased ;)

Why is that?

**Comment by jviotti** [comment]
Done! https://github.com/resin-io/etcher/pull/937

**Comment by lurch** [comment]
As they're both doing the same thing, wouldn't it be better for #937 to be merged into this PR ?

> Why is that?

I thought this might conflict with #934 , but apparently it doesn't.

**Comment by jviotti** [comment]
> As they're both doing the same thing, wouldn't it be better for #937 to be merged into this PR ?

Sounds good, done! I'll close the other one.

**Pull request merged**
