### PR TITLE
chore(ci): Limit git clone depth

### PR DESCRIPTION
**Pull request by jhermsmeier**
This may speed up cloning on CI services by reducing the clone depth.

Change-Type: patch

### CODE REVIEW

**Comment by jviotti** [comment]
Any reason why not doing depth 1?

**Comment by jhermsmeier** [comment]
Yeah, from https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth:

> Please note that if you use a depth of 1 and have a queue of jobs, Travis CI won’t build commits that are in the queue when you push a new commit.

And I figured we probably want to avoid that.

**Comment by lurch** [comment]
I wonder if that means that (effectively) there can only be as many jobs in the Travis build queue as the selected clone depth?
Given that Travis CI is often quite slow, and we often have many jobs queued up, I guess time will tell if a depth of 3 is 'enough' ;-)

**Comment by jviotti** [comment]
> I wonder if that means that (effectively) there can only be as many jobs in the Travis build queue as the selected clone depth?

Oh, is that indeed the case @jhermsmeier? As far as I can see, Travis CI clones the main branch of the repo (which after this change means the last 3 commits), but then calls `git fetch` on the branch like this:

```sh
git fetch origin +refs/pull/1272/merge:
```

Which means that the branch will always be fetched from the internet, and therefore the depth here doesn't apply.

Am I missing something?

**Comment by jhermsmeier** [comment]
Honestly, I don't really know, but from what I understood `depth: 1` is a special case, so build behavior shouldn't change.

**Comment by jviotti** [comment]
@lurch was right. This is causing failures when the Travis CI backlog is greater than 3. See:

- https://travis-ci.org/resin-io/etcher/jobs/220811455
- https://travis-ci.org/resin-io/etcher/jobs/220811463
- https://travis-ci.org/resin-io/etcher/jobs/220802663

I reverted this commit for now.

**Comment by lurch** [comment]
> @lurch was right.

Hah, lucky guess ;-)

**Comment by jhermsmeier** [comment]
Oh boy, sorry about that :/ Lesson learned.

**Pull request merged**
