### PR TITLE
style: use GNU Make `foreach` instead of a shell for loop

### PR DESCRIPTION
**Pull request by jviotti**
Just for conciseness and style.

Signed-off-by: Juan Cruz Viotti <jviotti@openmailbox.org>

### CODE REVIEW

**Comment by lurch** [comment]
...and portability :-)

(in my cross-platform Makefiles I define e.g. `COPY = cp` on Linux, `COPY = copy` on Windows, etc. And I use the presence of the ProgramFiles variable to check if I'm on Windows or not - bit hacky but it works :wink: )

**Comment by jviotti** [comment]
Where were you running `make` from? I've recently created a cross-platform Makefile for `node-static-entry-point` and I had to actually define `CP = cmd.exe /c` for it to work (see https://github.com/resin-io-modules/node-static-entry-point/blob/master/Makefile#L19)

**Comment by lurch** [comment]
> Where were you running make from?

Sorry, I was referring to a project that I've worked on for another client, nothing to do with resin or Etcher ;-)
(and I actually "cheated" a bit by using small parts of https://en.wikipedia.org/wiki/UnxUtils on Windows to give more consistent command-flag handling)

**Comment by lurch** [comment]
...I never needed to add any mentions of `cmd.exe` though, but I was using a MinGW build of GNU make.exe (ah, which I see your `node-static-entry-point` is also using). Weird.

**Comment by lurch** [comment]
(and I eventually ended up needing to use Makefile features which were only in the 4.x version of GNU make, so IIRC I compiled my own mingw version)

**Pull request merged**
