### PR TITLE
chore: Add a require() checking script

### PR DESCRIPTION
**Pull request by lurch**
This adds another sanity-check bash script to scan the Etcher source files
and check all required node modules are available.

More bash magic ;-)

### CODE REVIEW

**Comment by jviotti** [comment]
Very cool stuff! Do you think we can also do the opposite? e.g: complaining if there are unused dependencies?

**Comment by lurch** [comment]
> Do you think we can also do the opposite? e.g: complaining if there are unused dependencies?

Yup, can do, although that should be a separate script rather than adding extra functionality to this script.
Expect another PR later today... ;)

**Comment by lurch** [comment]
Obviously this is failing because of the typo that #1229 fixes.
@jviotti Do you want me to fix that typo in this PR, and then you can rebase #1229 after merging this PR, or would you rather merge #1229 first and then have me rebase this PR afterwards? ;-)

**Comment by jviotti** [comment]
Go ahead and create a PR. My PR will take a while before its ready to merge, given we've found out it breaks the drag n drop functionality.

**Comment by lurch** [comment]
See #1238

**Comment by lurch** [comment]
BTW...

> Do you think we can also do the opposite? e.g: complaining if there are unused dependencies?

Made a script to do that last night. It's still a bit rough around the edges (got some tidying up to do before PRing it, as there's a bunch of modules I need to whitelist) but it identified that the dependencies `file-tail` and `tail` are unused (as you've already fixed in #1242), and that the devDependency `electron-packager` is unused.

**Comment by jviotti** [comment]
> and that the devDependency electron-packager is unused.

This dependency is used by the build scripts, so that's probably the reason your script is not catching it.

**Comment by lurch** [comment]
Can you show me where? https://github.com/resin-io/etcher/search?utf8=✓&q=electron-packager

See also #897

**Comment by jviotti** [comment]
Oh, I got confused with `electron-builder`. Looks like `electron-packager` is indeed unused :+1:

**Pull request merged**
