### PR TITLE
style(GUI): capitalize every text for consitency purposes

### PR DESCRIPTION
**Pull request by jviotti**
As per @konmouz's request.

screenshot 2017-01-26 15 16 42
screenshot 2017-01-26 15 16 44
screenshot 2017-01-26 15 16 58
screenshot 2017-01-26 15 17 02
screenshot 2017-01-26 15 17 04

Fixes: https://github.com/resin-io/etcher/issues/881
Change-Type: patch
Changelog-Entry: Capitalize every text throughout the application.
Signed-off-by: Juan Cruz Viotti <jviotti@openmailbox.org>

### CODE REVIEW

**Comment by lurch** [comment]
As this also touches on the "marketing text" at the bottom of the window (changing it from UPPER CASE to Mixed Case), should we get @alisondavis17 's input on this?

**Comment by alisondavis17** [comment]
I think I am missing some context here, but I prefer the "marketing text" at the bottom of the window to match the other sentence-length text in the app, where not every word is capitalized. So I would prefer: "[ETCHER LOGO] is an open source project by [RESIN.IO LOGO]."

**Comment by jviotti** [comment]
Done!

screenshot 2017-01-26 20 10 30

**Comment by konmouz** [comment]
@jviotti, thanks. Are we also transferring settings to a modal window?

**Comment by jviotti** [comment]
@konmouz Yeah, we'll move the settings page to a modal and also update the main page to better match Zeplin's designs (e.g: remove number ordering, move the bar to be between the icons, etc).

**Pull request merged**
