### PR TITLE
docs: add an 'Announcing' section to PUBLISHING.md

### PR DESCRIPTION
**Pull request by lurch**

### CODE REVIEW

**Comment by jviotti** [comment]
I might be wrong, but I think talk.resin.io has been deprecated. @alexandrosm @craig-mulligan ?

**Comment by craig-mulligan** [comment]
@jviotti no we are reviving it to supplement gitter.

**Comment by jviotti** [comment]
I see. Do you know if there is a way we can trigger this automatically,
maybe as part of the CI builds?

On Tue, Nov 01, 2016 at 09:51:41AM -0700, Craig Mulligan wrote:
> @jviotti no we are reviving it to supplement gitter.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/resin-io/etcher/pull/814#issuecomment-257621326

-- 
Juan Cruz Viotti
Software Engineer

**Comment by jviotti** [comment]
Lets get this merged, and see if we can sort out automatic announcements later on.

@lurch Do you mind wrapping the text to match the rest of the file?

```diff
diff --git a/docs/PUBLISHING.md b/docs/PUBLISHING.md
index 3c40781..3f8eaf8 100644
--- a/docs/PUBLISHING.md
+++ b/docs/PUBLISHING.md
@@ -75,7 +75,8 @@ Run the following command:
 Announcing
 ----------

-Post a message to https://talk.resin.io/c/etcher/annoucements announcing the new version of Etcher, and including the relevant section of the Changelog.
+Post a message to https://talk.resin.io/c/etcher/annoucements announcing the
+new version of Etcher, and including the relevant section of the Changelog.

 [aws-cli]: https://aws.amazon.com/cli
 [cygwin]: https://cygwin.com
```

**Comment by lurch** [comment]
> @lurch Do you mind wrapping the text to match the rest of the file?

I _could_, but it might be easier you you to do that? (project maintainers have the power to edit PRs before merging)
As I made this change through the GitHub web interface, fixing it would involve adding another commit to this PR.

**Comment by lurch** [comment]
Regardless of this PR being merged, I guess https://talk.resin.io/c/etcher/annoucements should still be updated... ;-)

**Comment by WasabiFan** [comment]
> As I made this change through the GitHub web interface, fixing it would involve adding another commit to this PR.

That doesn't make a difference, because the maintainer who merges can squash your commits and change the message. I believe that @jviotti already does this with most PRs anyway to update the commit message for their format.

**Comment by lurch** [comment]
Fair enough - new commit added to this PR :)

**Comment by jviotti** [comment]
Right, we have "Squash and merge" enabled for this repository, which allows mergers to edit the final commit message. This has been proven to be super useful to gracefully deal with contributors that are not familiar with our commit guidelines.

**Comment by jviotti** [comment]
There you go: https://talk.resin.io/t/etcher-1-0-0-beta16-release/379

**Comment by lurch** [comment]
You linked to http://www.etcher.io instead of https://etcher.io/  ;-)

**Comment by jviotti** [comment]
I copied this from the v1.0.0-beta.15 announcement. I fixed the latest
one, but looks like I don't have enough permissions to edit the old one.
/cc @imreh

On Tue, Nov 01, 2016 at 06:21:26PM -0700, Andrew Scheller wrote:
> You linked to http://www.etcher.io instead of https://etcher.io/  ;-)
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/resin-io/etcher/pull/814#issuecomment-257746686

-- 
Juan Cruz Viotti
Software Engineer

**Pull request merged**
