### PR TITLE
fix(gui): Fix image checks in image selections

### PR DESCRIPTION
**Pull request by jhermsmeier**
I must have screwed something up during a rebase,
this mends the partition table an windows image checks.

Change-Type: patch

### CODE REVIEW

**Comment by lurch** [comment]
Could / should we add extra unit-tests to prevent similar mistakes getting through the CI checks in the future?

**Comment by jviotti** [comment]
The only thing I can think of to catch these types of issues, is to write GUI integration tests.

**Comment by lurch** [comment]
Oh? From what I can tell from the changes in this PR, it looks like the error was in the `selectImage` function, which currently doesn't seem to have any [unit-tests](https://github.com/resin-io/etcher/search?utf8=%E2%9C%93&q=selectImage&type=code) ?  Or is this code so heavily tied into the GUI that it's impossible to unit-test standalone (with mocking etc.)?

**Comment by lurch** [comment]
And on a related note, perhaps it'd be worth looking at adding some code-coverage checks to Etcher?

**Comment by jviotti** [comment]
> Or is this code so heavily tied into the GUI that it's impossible to unit-test standalone (with mocking etc.)?

Yeah, exactly. The code is too GUI centric to property unit-test. Spectron integration tests would cover these types of things.

> And on a related note, perhaps it'd be worth looking at adding some code-coverage checks to Etcher?

I'm a big fan of https://istanbul.js.org/, however I'm not sure how to configure it given that we use `electron-mocha` (a very custom wrapper around mocha that runs test cases on Electron itself), and that Electron applications have independent main/renderer processes. 

Let's definitely research what's needed. If its doable, then lets go for it!

**Pull request merged**
