### PR TITLE
upgrade(package): Bump mountutils 1.2.2 -> 1.3.8

### PR DESCRIPTION
**Pull request by jhermsmeier**
Change-Type: patch

### CODE REVIEW

**Comment by lurch** [comment]
Not **directly** related to this PR, but looking at https://github.com/resin-io-modules/mountutils/releases it seems that it's still only prebuilding x64 modules, and not prebuilding x86 modules?
(I just did some digging and found an old comment [here](https://github.com/resin-io-modules/mountutils/pull/58#issuecomment-338050404) )

**Comment by jhermsmeier** [comment]
@lurch then open an issue on mountutils instead of commenting off topic, please

**Comment by lurch** [comment]
Sorry Jonas, done that now https://github.com/resin-io-modules/mountutils/issues/62

**Comment by jhermsmeier** [comment]
@lurch is this good to merge though?

**Comment by jhermsmeier** [comment]
@jviotti there hasn't really been a change that impacts Etcher in a noticeable way, so I figured a changelog entry would be excess, but can add one

**Comment by jviotti** [comment]
Ah, alright, just making sure we didn't miss any important one.

**Pull request merged**
