### PR TITLE
feat(GUI): add progress gauges for multi-writes

### PR DESCRIPTION
**Pull request by Shou**
We add a new progress page where we display progress gauges or bars for
multi-writes. When there are too many gauges they change into bars.

Changelog-Entry: Add a progress page and progress gauges/bars for
multi-writes.
Change-Type: minor

### CODE REVIEW

**Comment by Shou** [comment]
Based on #1744. The codebase here isn't very clean yet while we work on the foundation of the functionality and the styles.

**Comment by jviotti** [comment]
@Shou Can you post screenshots?

**Comment by jviotti** [comment]
These are the design sketches, for reference purposes:

screen shot 2017-11-29 at 12 45 52 pm
screen shot 2017-11-29 at 12 46 10 pm

**Comment by Shou** [comment]
Current status: functional, UX isn't quite perfect, styles are very close to done, code isn't cleaned up

After `make electron-develop` you have to run `npm install` because of some shrinkwrap issues. To get back from the progress page, click the settings cog and then go back – hacky workaround!

**Comment by jhermsmeier** [comment]
NOTE: Please don't delete the branch; the multiwrites testing is still done off of this.

**Pull request closed without merging**
