### PR TITLE
doc: Add MSVC Build Tools option to Windows requisites

### PR DESCRIPTION
**Pull request by jhermsmeier**
Add Visual C++ 2015 Build Tools as a lighter option to a full blown Visual Studio installation for development requirements on Windows.

### CODE REVIEW

**Comment by jviotti** [comment]
Oh, very nice. I'll test this on my fresh Windows 8 installation to confirm it works :+1:

**Comment by lurch** [comment]
Indeed, very nice. Would it be worth updating Appveyor to use this?

**Comment by WasabiFan** [comment]
I have to ask... How'd you get a fresh Win8 installation?

**Comment by jviotti** [comment]
> Indeed, very nice. Would it be worth updating Appveyor to use this?

Appveyor machines include the full Visual Studio by default, so we can use that instead of having to install something custom.

> I have to ask... How'd you get a fresh Win8 installation?

You can download an ISO here: https://www.microsoft.com/en-us/software-download/windows8ISO

**Pull request merged**
