### PR TITLE
Change where the "Image Name" gets displayed, and display basename(imagepath) as a tooltip on the truncated imagename

### PR DESCRIPTION
**Pull request by lurch**
Fixes a couple of the problems identified in #716

### CODE REVIEW

**Comment by jviotti** [comment]
Looks good, but can we split these two changes as two separate commits? We rely on certain commit conventions to be able to auto-generate CHANGELOG, which becomes an issue if two changes are mixed in a single patch.

**Comment by lurch** [comment]
No problem, will do.

**Comment by lurch** [comment]
#745 

I can't create a PR for the other part of this PR yet though, because the two changes would conflict. (so after #745 has been merged into master, I can create a new PR)

**Comment by WasabiFan** [comment]
You could also just add two separate commits to the same PR. As long as you follow their commit conventions, it should work out fine.

**Comment by lurch** [comment]
I dunno what resin.io's commit conventions are yet, but I _personally_ prefer one commit per PR.

**Comment by WasabiFan** [comment]
You can look at any commit in their commit history to see the items they used. Compared to waiting for the first PR before making the second round of changes, adding an additional commit seems a lot simpler! In the end you wouldn't even need to generate a merge commit if they asked GitHub to rebase on merge.

**Comment by lurch** [comment]
> You can look at any commit in their commit history to see the items they used.

Good point :+1: 

@jviotti would #745 be a 'feat(GUI)' or a 'style(GUI)' ? (or something else?)

**Comment by alexandrosm** [comment]
but this raises the point that we should document what we're doing with our
commit convention. It's really cool stuff using the versionist project, and
I'm sure juanchi will want to spend more time writing it up next week, when
he's freed up from the first batch of the reconfiguration work.

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by WasabiFan** [comment]
> but this raises the point that we should document what we're doing with our commit convention.

Isn't that this? https://github.com/resin-io/etcher/blob/master/docs/COMMIT-GUIDELINES.md

**Comment by alexandrosm** [comment]
@lurch -- there you go :)

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by lurch** [comment]
Oops, I managed to miss that! \*embarrased\*

@alexandrosm Maybe you could make use of https://help.github.com/articles/setting-guidelines-for-repository-contributors/ ?

**Comment by jviotti** [comment]
The tooltip is definitely a feature IMO, while the other one is more of a style. We should definitely write a CONTRIBUTING document that serves as an entry point to the other documentation files (like a toc, or something like that).

**Comment by alexandrosm** [comment]
@lurch *I* managed to miss that also. I should have had more faith in
@jviotti's relentless drive to document everything :D

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Pull request closed without merging**
