### PR TITLE
docs: suggest UNetbootin if user requires setting persistence storage

### PR DESCRIPTION
**Pull request by jviotti**
See: https://github.com/resin-io/etcher/issues/413
See: https://github.com/resin-io/etcher/pull/783#issuecomment-256959050
Signed-off-by: Juan Cruz Viotti <jviotti@openmailbox.org>

### CODE REVIEW

**Comment by lurch** [comment]
Oooh, that's an interesting side-observation I've just made: after reading https://unetbootin.github.io and https://sourceforge.net/p/unetbootin/wiki/howitworks/ it looks like UNetbootin doesn't actually write the ISO directly to the raw device (as etcher would), but instead extracts the individual files from the ISO, and writes them to an already-FAT32-formatted partition.

**Comment by jviotti** [comment]
@lurch Yeah, they also install a boot loader on top, such as GRUB. We discussed implementing this "write" mechanism in Etcher, but we never allocated any serious work for it.

**Comment by alexandrosm** [comment]
@lurch echoes of noobs?

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by lurch** [comment]
Sort of, except a) NOOBS _does_ partition and format the SD card itself (and so therefore has multiple partitions rather than just one) and b) NOOBS deals with tarballs rather than ISO files ;-)

**Pull request merged**
