### PR TITLE
doc(README): Update & normalize badges

### PR DESCRIPTION
**Pull request by jhermsmeier**
This updates & normalizes the badges in the README to all have
a consistent style and adds a release-badge pointing to the website.

Change-Type: patch

### CODE REVIEW

**Comment by lurch** [comment]
The number on the waffle icon seems to be white text on a light-gray background, and therefore totally unreadable?

**Comment by jhermsmeier** [comment]
@lurch yeah – that'd be due to https://github.com/badges/shields/issues/620 – and will prob. be fixed sooner or later. Not sure if we'd want to fall back to the previous (which also displayed an incorrect count), or just use this and it'll resolve itself somehow at some point.

**Comment by jviotti** [comment]
Let's keep the new one. The badges provider will definitely fix it (can we actually let them know that its unreadable btw?).

**Comment by jhermsmeier** [comment]
Created a new issue for this particular case: https://github.com/badges/shields/issues/1008

**Comment by lurch** [comment]
@jhermsmeier Fancy also updating https://github.com/resin-io-modules/drivelist ? :)

**Comment by jhermsmeier** [comment]
@lurch haha, yeah, can do :)

**Pull request merged**
