### PR TITLE
chore: set msvs version on `dependencies-npm.sh` when running on Windows

### PR DESCRIPTION
**Pull request by jviotti**
Signed-off-by: Juan Cruz Viotti <jviotti@openmailbox.org>

### CODE REVIEW

**Comment by lurch** [comment]
> maybe neither on GNU/Linux

Just FYI: On Ubuntu 14.04 I get:
```bash
$ uname -o
GNU/Linux
```

**Comment by lurch** [comment]
Might be better to move this detection into the `Makefile`, where all the rest of the uname-detection is being done? \*shrug\*

**Comment by jviotti** [comment]
@lurch Sure, lets make this script take an "operating system" option.

**Comment by jviotti** [comment]
Done!

**Comment by lurch** [comment]
Much nicer :-)

**Comment by jviotti** [comment]
Haha, I totally agree!

**Pull request merged**
