### PR TITLE
doc(README): add install and uninstall instructions for Solus

### PR DESCRIPTION
**Pull request by Jacalz**
This adds the required steps to installing and uninstalling Etcher on Solus Linux.

Change-Type: patch
Changelog-Entry: Add instructions for installing and uninstalling on Solus.

### CODE REVIEW

**Comment by Jacalz** [comment]
I think this should suffice, please have a look when you have time @jhermsmeier

**Comment by lurch** [comment]
@Jacalz I just noticed the `+` in front of the `sudo` in the [uninstall section](https://github.com/balena-io/etcher/blob/master/README.md#uninstall-2). I've never used Solus Linux, but is that a typo?

**Comment by Jacalz** [comment]
@lurch Yes tjat is indeed a typo. I am sorry for that 😅

**Comment by Jacalz** [comment]
A have now sent in a PR to fix that typo @lurch, see https://github.com/balena-io/etcher/pull/2595

**Pull request merged**
