### PR TITLE
feat(GUI): display a loading page when updating

### PR DESCRIPTION
**Pull request by Shou**
We add an updating overlay that should only be shown during updates for
the Etcher Pro. This can be set using the `updatingState` field in the
Redux store, and setting it to `true`, and `false` when finished. We may
extend this to become an object containing more metadata in the future.

Closes: #2312
Change-Type: patch

### CODE REVIEW

**Comment by Shou** [comment]
image

**Comment by curcuz** [comment]
@Shou this needs to be a PNG image file that is pushed directly to the framebuffer via `fbi`

**Comment by Shou** [comment]
In that case this should do, right? I just exported the mock-up and added square edges.

untitled

**Comment by jhermsmeier** [comment]
Closing, as incorrect solution

**Pull request closed without merging**
