### PR TITLE
feat(GUI): change success page fallback message

### PR DESCRIPTION
**Pull request by Shou**
We change the success page's fallback message from "Thank you for using
Etcher" to "We hope you enjoyed using Etcher".

Changelog-Entry: Change success page fallback message.

### CODE REVIEW

**Comment by Shou** [comment]
@konmouz just to check, this is the message we wanted right?

**Comment by konmouz** [comment]
@Shou, I think so. But it would be good to double check with @alexandrosm

**Comment by jviotti** [comment]
Didn't we decide that this new message implied that were thankful more than the other way around?

**Comment by lurch** [comment]
@Shou Could you update the commit-message? According to the diff, the message used to be "Thanks for using..." rather than "Thank you for using..."
Also, this should be `style` rather than `feat`.
And you'll need to rebase onto latest `master` to get the CI tests passing.

**Comment by jviotti** [comment]
Ping @konmouz @Shou @alexandrosm. Is this change something we discussed somewhere?

**Comment by Shou** [comment]
We are no longer using the banner where this is relevant, closing this.

**Pull request closed without merging**
