### PR TITLE
upgrade: `elevator` to v2.2.2

### PR DESCRIPTION
**Pull request by jviotti**
This version prints debug messages to `stdout`.

See: https://github.com/resin-io-modules/elevator/pull/11
Signed-off-by: Juan Cruz Viotti <jviotti@openmailbox.org>

### CODE REVIEW

**Comment by lurch** [comment]
Shouldn't this have bumped the shrinkwrap too?

**Comment by jviotti** [comment]
This is an optional dependency, which is not tracked by shrinkwrap.

**Comment by lurch** [comment]
Ahhh. Does that mean we'll always get the latest version installed anyway?

**Comment by jviotti** [comment]
Yeah, that's right, but there is not much we can do about that, given that NPM shrinkwrap has some known limitations with regarding to optional dependencies. Maybe we should at least lock the version in package.json?

**Comment by jviotti** [comment]
@lurch Maybe this is something to add to the integrity checks (e.g: optional dependencies can't have ranges)?

**Pull request merged**
