### PR TITLE
refactor(image-stream): get rid of `gzip-uncompressed-size`

### PR DESCRIPTION
**Pull request by jviotti**
Signed-off-by: Juan Cruz Viotti <jviotti@openmailbox.org>

### CODE REVIEW

**Comment by lurch** [comment]
:-1: 
IMHO for something as low-level / technically-tricky as this, it makes _far_ more sense to use a 3rd-party module, rather than rolling our own code. Unless there's very compelling reasons otherwise...

**Comment by jhermsmeier** [comment]
For reading a uint32 from the end of a file? I not sure I see how that's technically tricky ;)
Also, the 3rd party module we've been using was written by @jviotti and this is just an adjusted copy of https://github.com/jviotti/node-gzip-uncompressed-size/pull/1, as discussed there

**Comment by lurch** [comment]
> Also, the 3rd party module we've been using was written by @jviotti

Ahh, I'd totally missed that ;-)
I guess in that case we have total control over its dependencies, so why does it need "de-modularising" ?

**Comment by jviotti** [comment]
I rather have it inside Etcher, since its something we will want to keep tweaking and improving specifically for Etcher. Once we start publishing the SDK, this functionality will be re-usable through the image stream module, so we won't affect distributability at all.

**Pull request merged**
