### PR TITLE
fix(gui): Increase height of webview

### PR DESCRIPTION
**Pull request by craig-mulligan**
connects to #1856

Change-Type: patch

### CODE REVIEW

**Comment by jhermsmeier** [comment]
Can you add before & after screenshots for a quick visual impression?

**Comment by jhermsmeier** [comment]
Ci is failing because the sass changes aren't committed ;)

**Comment by craig-mulligan** [comment]
The sass is committed? Should I build em too?

**Comment by craig-mulligan** [comment]
screen shot 2017-11-17 at 13 34 52
screen shot 2017-11-17 at 13 37 10

**Comment by lurch** [comment]
That second screenshot isn't what Etcher currently shows on success, which is actually this:
image

**Comment by jhermsmeier** [comment]
> The sass is committed? Should I build the css?

@craig-mulligan yeah, sorry – that's what I meant

**Comment by craig-mulligan** [comment]
Oh @lurch - okay that `flash again` doesn't come up on my screen, I'm testing manually be setting the `success` state. I can't test it properly because etcher fails on my machine. (looks like elevation issues). So maybe there isn't actually more room to be used. @lurch do you mind pulling and testing this on your machine?

**Comment by craig-mulligan** [comment]
If not, don't worry about it. I don't think this is v urgent.

**Comment by craig-mulligan** [comment]
Yea defo's looks like the height used curbed to maintain that flash complete status. - closing.

**Comment by jhermsmeier** [comment]
@craig-mulligan what kind of elevation issues are you running into? Are you on current master?

**Comment by craig-mulligan** [comment]
@jhermsmeier yea, but it's happening with my standard etcher `1.1.2` as well. It happened a couple weeks ago, assumed it was the drive but looks like it's my machine. In the way of errors nothing throws, it starts and then just logs elevation cancelled as second later.

**Comment by jhermsmeier** [comment]
@craig-mulligan can you pull again & run `make electron-develop` before starting it? – This should have been fixed on current master, but your dependencies might be stale.

**Comment by craig-mulligan** [comment]
@jhermsmeier I get the same result. I'll open an separate issue for this.

**Pull request closed without merging**
