### PR TITLE
chore: add debian packaging

### PR DESCRIPTION
**Pull request by dlech**
This adds a "debian" command to the linux build script. It uses
electron-installer-debian to create a debian package.

### CODE REVIEW

**Comment by dlech** [comment]
Trying out an alternate packaging method. You can get the package created from this commit at <https://bintray.com/dlech/etcher-deb/etcher-electron> (as soon as it is done uploading).

**Comment by dlech** [comment]
In this one, both the package and the executable are named `etcher-electron`.

**Comment by jviotti** [comment]
This PR looks amazing! I've noticed that the `debian` build command doesn't package things by itself, therefore if you run it without having ran `package` first, you get errors like these ones:

```sh
+ cp scripts/build/debian/etcher-electron.sh etcher-release/Etcher-linux-x64/
cp: cannot create regular file 'etcher-release/Etcher-linux-x64/': No such file or directory
```

Making sure the packaging section runs of `command == debian` seems to be the way to go:

```diff
diff --git a/scripts/build/linux.sh b/scripts/build/linux.sh
index 514f136..492b571 100755
--- a/scripts/build/linux.sh
+++ b/scripts/build/linux.sh
@@ -169,7 +169,7 @@ if [ "$COMMAND" == "install" ] || [ "$COMMAND" == "all" ]; then
   fi
 fi
 
-if [ "$COMMAND" == "package" ] || [ "$COMMAND" == "all" ]; then
+if [ "$COMMAND" == "package" ] || [ "$COMMAND" == "debian" ] || [ "$COMMAND" == "all" ]; then
   if [ "$ARCH" == "x86" ]; then
     package_x86 etcher-release
   fi
```

As a side note, this scripts are getting very hairy now that there are multiple distribution methods, but don't worry about it, I'll allocate some time to clean it up next week!

**Comment by jviotti** [comment]
Ah wait, the `install` step is not being done as well, and by checking other targets, like `appimage`, looks like the way it is is enough, so ignore my previous comment :)

**Comment by jviotti** [comment]
Thanks a lot! Lets figure out the Bintray publishing step now. I'll get a Resin.io Bintray account and share the key and other needed details.

**Pull request merged**
