### PR TITLE
chore: fix CI script to work when 'require'ing nested modules

### PR DESCRIPTION
**Pull request by lurch**

### CODE REVIEW

**Comment by lurch** [comment]
Afraid I'm now going out for the evening, but I can't merge this yet because the CI builds are being slow. Feel free to merge it in my absence!

**Comment by jviotti** [comment]
The new changes seem to get confused with:

```
lib/gui/modules/analytics.js requires '../../../bower_components/mixpanel/mixpanel-jslib-snippet.js' module which can't be located
```

**Comment by lurch** [comment]
Isn't that warning correct, given that bower has now been removed??

**Comment by lurch** [comment]
Mended.

**Comment by jviotti** [comment]
> Isn't that warning correct, given that bower has now been removed??

Not really. Bower is being removed by https://github.com/resin-io/etcher/issues/1208, but that PR didn't get merged yet.

> EDIT: Ah, oops. I also 'refactored' the script in this PR to only look for require('*.json'), I didn't realise there'd also be require('*.js') !?

Not sure what you mean. Is there a `require('*.js')` or a `require('*.json')` call somewhere in our code? I don't think CommonJS is able to resolve that correctly. What are we doing in this script in that case?

**Comment by lurch** [comment]
> Not really. Bower is being removed by #1208, but that PR didn't get merged yet.

Yeah, I developed this PR against a local clone of #1208 and forgot to test directly against `master`, which is how this mistake slipped through (on the first iteration of this PR).

> Not sure what you mean. Is there a require('*.js') or a require('*.json') call somewhere in our code?

Apologies for the confusion. I meant I'd adapted the code to match against `\.json$` e.g. `require('package.json')`, which meant that it broke when it came across e.g. `require('../../../bower_components/mixpanel/mixpanel-jslib-snippet.js')`. Fixed by updating the regex to `\.js(on)?$`.

**Pull request merged**
