### PR TITLE
fix(webpack): Add etcher.js to webpack build

### PR DESCRIPTION
**Pull request by thundron**
Build electron the electron main process js file to include internal settings module

Change-type: patch
Signed-off-by: Lorenzo Alberto Maria Ambrosi <lorenzoa@resin.io>

### CODE REVIEW

**Comment by thundron** [comment]
@resin-ci retest

**Comment by thundron** [comment]
@resin-ci retest

**Comment by thundron** [comment]
@resin-ci retest

**Comment by thundron** [comment]
@resin-ci retest

**Comment by zvin** [comment]
@thundron travis is failing, is this expected?

**Comment by thundron** [comment]
@zvin Actually yes, we're moving away from travis and will rely on resin-concourse running the tests and handling the app build internally, which is more reliable since it's updated while the repo's tests are not

**Pull request merged**
